"""
Report Generator

Renders mining daily reports using Jinja2 templates.
"""

import os
from datetime import datetime

from jinja2 import Environment, FileSystemLoader

from .state import AgentState

_TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")

_DEFAULT_TEMPLATE = """\
# {{ target }} {{ commodity }} Daily Report

**Date:** {{ date }}
**Scope:** {{ scope }}

---

## Key Highlights

{% if news %}
- {{ news|length }} news articles retrieved
{% endif %}
{% if prices %}
{% for key, data in prices.items() %}
{% if data and not data.error %}
- {{ data.commodity }}: {{ data.price }} {{ data.unit }}
{% endif %}
{% endfor %}
{% endif %}

---

## News Summary

{% if news %}
{% for article in news[:5] %}
### {{ article.title }}

- **Published:** {{ article.get('published_at', 'N/A') }}
- **URL:** {{ article.get('url', '') }}
- **Summary:** {{ article.get('summary', 'No summary available')[:300] }}

{% endfor %}
{% else %}
*No news articles found for the specified query.*
{% endif %}

---

{% if fetch_contents %}
## Article Details

{% for content in fetch_contents[:3] %}
{% if content and content.get('content') %}
### {{ content.get('title', 'Untitled') }}

{{ content.get('content', '')[:1000] }}

{% endif %}
{% endfor %}
{% endif %}

---

## Resource Changes

{% if resources and not resources.get('error') %}
| Category | Value |
|----------|-------|
| Measured | {{ resources.get('measured_mt', 0) }} Mt |
| Indicated | {{ resources.get('indicated_mt', 0) }} Mt |
| Inferred | {{ resources.get('inferred_mt', 0) }} Mt |
| **Total** | **{{ resources.get('total_mt', 0) }} Mt** |
| Grade (Li2O) | {{ resources.get('grade_li2o', 'N/A') }} |
| Report Type | {{ resources.get('report_type', 'Unknown') }} |
{% else %}
*No resource data available for today.*
{% endif %}

---

## Market Price Trends

{% if prices %}
{% if prices.get('current') and not prices.current.get('error') %}
### Current Price
- **{{ prices.current.commodity }}**: {{ prices.current.price }} {{ prices.current.unit }}
- **Date**: {{ prices.current.date }}
{% endif %}

{% if prices.get('trend') and not prices.trend.get('error') %}
### Price Trend ({{ prices.trend.get('period_days', 7) }} days)
- **Current**: {{ prices.trend.current }} {{ prices.trend.unit }}
- **7-Day Change**: {{ prices.trend.change_7d }} ({{ prices.trend.change_pct }}%)
- **Volatility**: {{ prices.trend.volatility }}%
- **Trend**: {{ prices.trend.trend }}
{% endif %}
{% else %}
*No price data available.*
{% endif %}

---

## Risk Alerts

{% set has_risks = false %}
{% if prices and prices.get('trend') and not prices.trend.get('error') %}
{% if prices.trend.change_pct < -3 %}
- High volatility detected: {{ prices.trend.change_pct }}% decline over {{ prices.trend.period_days }} days
{% set has_risks = true %}
{% endif %}
{% endif %}

{% if errors %}
{% for error in errors %}
- System alert: {{ error }}
{% set has_risks = true %}
{% endfor %}
{% endif %}

{% if not has_risks %}
*No significant risks identified.*
{% endif %}

---

## Data Sources

{% if news %}
{% for article in news[:10] %}
- {{ article.get('title', 'Untitled') }} ({{ article.get('source', 'Unknown') }})
{% endfor %}
{% endif %}

---

*Report generated by Mining Daily Agent at {{ date }}*
"""


def render_report(state: AgentState) -> str:
    """Render the full markdown report from agent state."""
    env = Environment(loader=FileSystemLoader(_TEMPLATE_DIR))

    try:
        template = env.get_template("report.md.j2")
    except Exception:
        template = env.from_string(_DEFAULT_TEMPLATE)

    context = {
        "target": state.get("target", "Unknown"),
        "commodity": state.get("commodity", "Unknown"),
        "scope": state.get("scope", "today"),
        "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "news": state.get("news", []),
        "fetch_contents": state.get("fetch_contents", []),
        "resources": state.get("resources", {}),
        "prices": state.get("prices", {}),
        "errors": state.get("errors", []),
    }

    return template.render(**context)
